### ISSUE TITLE
Some expectations

### ISSUE THREAD

**Issue by bigleaffrog** [smrt-model/smrt#21]
Do you have any plans to convert this code into C++or MATLAB language code?Is there a plan to add a 3D model electromagnetic scattering calculation module?

Looking forward to your reply.

**Comment by ghislainp** [comment]
No there is not plan to convert to a different language. SMRT is fast despite being written in Python. The computational bottleneck is often in the diagonalisation of matrices, which is handled very efficiently with underlying LAPACK. A Fortran / C++ code would be marginally faster.

Regarding 3D, this is not in our todo list but could be done with some significant work.
