### ISSUE TITLE
Extracting the layer extinction coefficient

### ISSUE THREAD

**Issue by carlettif** [smrt-model/smrt#31]
Good morning all,

I have tried for a bit without success, so I will try asking for help here: when running a simulation with SMRT, is there a way to extract the extinction coefficient (or scattering and absorption coefficients) for each layer of snow and store it as a value?

Thank you very much,

Francesca

**Comment by ghislainp** [comment]
Yes, ks and ka are available in the result object returned by model.run

See the documentation of the Result api. Or here:

https://github.com/smrt-model/smrt/blob/master/smrt/core/result.py


Le 7 août 2024 11:55:29 GMT+02:00, carlettif ***@***.***> a écrit :

**Comment by carlettif** [comment]
Thank you very much!
