### ISSUE TITLE
Bug in make_medium.py

### ISSUE THREAD

**Issue by JulienMeloche** [smrt-model/smrt#4]
Hi,
I'm trying to simulate Tb from soil only by adding a transparent layer.

First, what is the best way to do this?
My idea was to use make_generic_stack to use make soil with a transparent layer with ka = 0, ks = 0 and effective_permittivity = 1.

Second,
When using make_generic_stack from make_medium, I get the following error saying 'get' is not define. I quickly fixed this adding 'lib.' at line 445 of make_medium.py

![Selection_001](https://user-images.githubusercontent.com/48692279/63189985-3796b700-c033-11e9-8941-473fa53c2fba.png)

Should we submit a pull-request?

Julien et Paul

**Comment by ghislainp** [comment]
Yes please podt a PR. I think the transparent layer is the best, I'll see later today if I can make this automatic.
