### ISSUE TITLE
Substrate with geometrical_optics or iem_fung92

### ISSUE THREAD

**Issue by JulienMeloche** [smrt-model/smrt#6]
Hi, 
I've seen you have been working lately on geometrical_optics and iem_fung92, interface and substrate module. I don't know if they are ready to use since no documentation appears on SMRT/doc but I'm having this same issue when I try to run both module for substrate. It will be very useful If I can work with correlation length for my soil roughness work I've presented at the workshop...

![code_errorGEo](https://user-images.githubusercontent.com/48692279/65250135-19552880-dac3-11e9-974a-6c4a560e5e97.jpg)

Here's the error I get, it is the same for both module and I also get the same thing if I replace the generic stack by a snowpack.

![error_substrate_geo](https://user-images.githubusercontent.com/48692279/65250150-1eb27300-dac3-11e9-91fa-a62660b5209d.jpg)

Thank you again for your time,
Julien

**Comment by ghislainp** [comment]
Thanks. I see, it is a serious problem. I've change something deep that should solve your problem. Please test and let me know if it sloves your issue.

**Comment by JulienMeloche** [comment]
Here's now the error I'm getting
![issueGeo2](https://user-images.githubusercontent.com/48692279/65269284-dd33bf00-dae6-11e9-96a2-de8e592b21c7.jpg)
